model:
  # name: 'Salesforce/codet5-small'
  name: 't5-small'
  cls: 'transformers.T5ForConditionalGeneration'
  type: 'seq2seq'
data:
  dataloader:
    tokenizer:
      # cls: 'transformers.RobertaTokenizer'
      cls: 'transformers.T5Tokenizer'
      pad_token_id: 0
      eos_token_id: 2
      abr: t5-small
    batch_size: 4 # reduced from 8

trainer:
  accumulate_grad_batches: 64