model:
  name: 'Salesforce/codet5-small'
  cls: 'transformers.T5ForConditionalGeneration'
  type: 'seq2seq'
data:
  dataloader:
    tokenizer:
      cls: 'transformers.RobertaTokenizer'
      pad_token_id: 0
      eos_token_id: 2
      abr: codet5-small